const paragraphs = [
  "Once upon a time",
  "Once upon a time, in a land far away, lived a hamster named Andy.",
  "Once upon a time, in a land far away, lived a turtle named Leonardo. Leonardo was one of the 4 teenage mutant ninja turtles!",
  "Once upon a time, in a deep forest, there lived a curious little squirrel named Barni. He loved exploring the forest and collecting shiny acorns! One day, Barni collected 10 acorns from 3 oak trees.",
  "Once upon a time, in a faraway land, a curious little robot named Byte lived. Byte loved exploring the digital world and collecting bits of data. One day, Byte collected 10 files from 3 different servers. Later that day, Byte spotted its friend and sent a message, 'Hello, Pixel!'.",
  "In DataTown, Alex used SQL to manage a database of 100 books. They queried the Books table to find titles by their favorite author, J.K. Rowling, who wrote 7 books in the Harry Potter series: SELECT title FROM Books WHERE author = 'J.K. Rowling'; Alex discovered 5 new stories and shared them with 20 friends.",
  "In a digital world, a young coder learned to build web pages with HTML, add vibrant styles using CSS and hex colors like #8b4513, and manage data efficiently with SQL. As they progressed, they discovered how to combine these skills to create interactive & visually appealing websites, making them a versatile developer in the tech community ~ where coding magic happens!",
  'Once upon a time, in a faraway land, a curious little squirrel named Sammy learn about HTML. A HyperText Markup Language used to create interactive web pages in the World Wide Web. So he decided to create an HTML element with hyperlink. <h1 style="color: rgb(123,90,180);">Welcome to the <a href="https://google.com/maps/place/Magic+forest/@41.6637029,44.699254,14z">magic forest</a> with acorns</h1>',
  'Once upon a time, in a faraway land, a curious little squirrel named Sammy learn about CSS. A Cascading Style Sheets used to format the layout of a web page in the World Wide Web. So he decided to create very long CSS selector. @media screen {body > div:first-child + ul:nth-child(3) > li:not([class]) + li[id]:nth-child { border-bottom: 1rem solid rgba(12,45,90,0.5); border-bottom; border-bottom-right-radius: 50px 20%;}}',
  "Once upon a time, in a faraway land, a curious little squirrel named Sammy learn about Python. Python is a high-level, general-purpose programming language.  He started from simple dictionary: double_language_palindrom = { 'როგორ': 'как', 'ლოლ': 'lol'}, but then he decided to convert it to a list of tuples: [(key, value) for key, value in double_language_palindrom.items()]",
  "Once upon a time, in a faraway land, a curious little squirrel named Sammy learn about Python. Python is a high-level, general-purpose programming language. It's design philosophy emphasizes code readability with the use of significant indentation. Here is an one-liner Sieve of Eratosthenes that demonstrates the power and conciseness of Python coding: reduce( (lambda r,x: r-set(range(x**2,n,x)) if (x in r) else r), range(2,int(n**0.5)), set(range(2,n)))",
  'Once upon a time, in a faraway land, a curious little squirrel named Sammy learn about Python. Python is a high-level, general-purpose programming language. Design philosophy of the languaage emphasizes code readability with the use of significant indentation. Here is an one-liner that prints all words in list that are present in sentence: print([word for word in list if word in ("".join(word for word in sentence.lower() if word.isalpha() or word.isnumeric() or word == " ")).split(" ")])',
];
