const paragraphs = [
  "Once upon a time",
  "Once upon a time, in a land far away, lived a squirrel named Sammy.",
  "Once upon a time, in a land far away, lived a squirrel named Sammy. Sammy loved exploring the forest, finding shiny acorns.",
  "Once upon a time, in a faraway land, a curious little squirrel named Sammy lived. He loved exploring the forest and collecting shiny acorns. One day, he collected 10 acorns from 3 oak trees.",
  'Once upon a time, in a faraway land, a curious little squirrel named Sammy lived. He loved exploring the forest and collecting shiny acorns. One day, he collected 10 acorns from 3 oak trees. Later that day, he spotted his friend and called out, "Hello, Lilly!".',
  'Once upon a time, in a faraway land, a curious little squirrel named Sammy lived. He loved exploring the forest and collecting shiny acorns. One day, he collected 10 acorns from 3 oak trees. Later that day, he spotted his friend and called out, "Hello, Lilly!". Lilly, a friendly deer, pricked her ears up and turned to look at Sammy.',
  'Once upon a time, in a faraway land, a curious little squirrel named Sammy learn about SQL. A Structured Query Language used to manage data, especially in a relational database management system. So Sammy decided to create a table of acorns: "CREATE TABLE acorns (acorn_id INTEGER PRIMARY KEY, tree_type TEXT, number_of_acorns INTEGER);"',
  'Once upon a time, in a faraway land, a curious little squirrel named Sammy learn about HTML. A HyperText Markup Language used to create interactive web pages in the World Wide Web. So he decided to create an HTML element with hyperlink. <h1 style="color: rgb(123,90,180);">Welcome to the <a href="https://google.com/maps/place/Magic+forest/@41.6637029,44.699254,14z">magic forest</a> with acorns</h1>',
  'Once upon a time, in a faraway land, a curious little squirrel named Sammy learn about CSS. A Cascading Style Sheets used to format the layout of a web page in the World Wide Web. So he decided to create very long CSS selector. @media screen {body > div:first-child + ul:nth-child(3) > li:not([class]) + li[id]:nth-child { border-bottom: 1rem solid rgba(12,45,90,0.5); border-bottom; border-bottom-right-radius: 50px 20%;}}',
];
