const paragraphs = [
  "Once upon a time.", // Grade 1: Basic punctuation practice
  "Once upon a time, in Tbilisi's vibrant forests, lived a clever hamster named Andy. Andy gathered 12 shiny acorns daily and shared them with friends.", // Grade 2: Simple sentences, numbers
  "Once upon a time, in a distant land near the Black Sea, lived a wise turtle named Leonardo. Leonardo explored ancient ruins with his three brothers, solving puzzles and discovering treasures under starry skies.", // Grade 3: Compound sentences, geography
  "In Tbilisi's Mtatsminda Park, a curious squirrel named Barni collected 15 acorns from four oak trees. 'What a bountiful harvest!' Barni exclaimed, while sharing nuts with birds and rabbits.", // Grade 4: Dialogue, exclamation, counting
  "In Georgia's digital valleys, a robot named Byte explored networks, collecting 20 data packets from five servers. Byte messaged its friend: 'გამარჯობა, Pixel! Let's code an app for Vardzia caves.'", // Grade 5: Bilingual, tech intro
  "At GAHS ICT Lab, Alex queried a library database with SQL: SELECT title, pages FROM Books WHERE author = 'ლაშა ბურდული' AND pages > 300 ORDER BY title; This revealed 8 epic tales, shared with 25 classmates via GitHub.", // Grade 6: SQL, local author nod, sorting
  "In 2026's web era, coders master HTML5 for structure, CSS Grid for responsive layouts (e.g., grid-template-areas: 'header header' 'sidebar main'), and JavaScript for interactivity like fetch('/api/tbilisi-events').then(data => console.log(data.events));", // Grade 7: Modern web stack
  `Once upon a time in Tbilisi, squirrel Sammy studied HTML5. It structures web pages with semantic tags. Sammy built: <header><h1 style="font: 2rem 'Noto Serif Georgian'; color: hsl(200, 70%, 40%);">გამსვლელი მაგიის ბაღი</h1><a href="https://maps.app.goo.gl/tbilisi-old-town">Old Tbilisi</a></header>`, // Grade 8: Semantic HTML, Georgian font/CSS
  `Sammy then tackled CSS3 for styling. Using advanced selectors: @media (prefers-reduced-motion: no-preference) { main:has(.tbilisi-card) > article:nth-child(odd)::before { background: linear-gradient(45deg, #ff6b35, #f7931e); border-radius: 1rem; } }`, // Grade 9: Media queries, pseudo-elements
  `In Python 3.12, Andy learned type hints and f-strings. He coded: cities: dict[str, int] = {'თბილისი': 1_200_000, 'კუთaisi': 150_000}; print(f"Population: {cities['თბილისი']:,} in {max(cities, key=cities.get)}!");`, // Grade 10: Modern Python, f-strings, Georgian keys
  `Sammy optimized algorithms in Python: def prime_gen(n: int) -> list[int]: return [p for p in range(2, n) if all(p % d for d in range(2, int(p**0.5)+1))]; primes = prime_gen(101); print(f"Primes under 101: {len(primes)} → {primes[:5]}");`, // Grade 11: Type hints, list comps, math
  `For cybersecurity at GAHS, students practiced: import hashlib; password = "Secure2026#GE"; hashed = hashlib.sha256(password.encode()).hexdigest(); print(f"SHA-256: {hashed[:16]}... Verify: {hashlib.sha256(b'Secure2026#GE').hexdigest() == hashed}");`, // Grade 12: Hashing, security basics
];
